### ISSUE TITLE
[BUG] [❗] WebSocket does not appear to be live! Restarting the WebSocket connection...

### ISSUE THREAD

**Issue by Freekers** [FungY911/better-grass#7]
**Describe the bug**
Connection keeps closing every 2-3 seconds:
```
172.21.0.1 [OPEN] Websocket is open

172.21.0.1 [CLOSE] Connection closed, code=1006, reason=

172.22.0.1 [❗] WebSocket does not appear to be live! Restarting the WebSocket connection...

172.22.0.1 [OPEN] Websocket is open

172.22.0.1 [CLOSE] Connection closed, code=1006, reason=
```

**To Reproduce**

docker-compose:
```
services:
  grass:
    image: fungyx/better-grass:latest
    container_name: grass
    network_mode: "host"
    environment:
      - USER_IDS=XXXXXXXX
    restart: unless-stopped
```

Alternative also doesn't work:

```
services:
  grass:
    image: fungyx/better-grass:latest
    container_name: grass
    network_mode: "host"
    command: USER_IDS=XXXXXXXXXXXX
    restart: unless-stopped
```

**Operating System (please complete the following information):**
Ubuntu 22.04
